(()=>{const s=document.createElement('script');s.src='site-integration.js';s.defer=true;document.head.appendChild(s);})();
document.addEventListener('DOMContentLoaded',()=>{
  const sets={
    general:{title:'General Tender Submission Checklist',items:['Read the full tender / RFQ from beginning to end.','Record tender reference, closing date, closing time and submission location.','Check tender-document fee and obtain proof of purchase where required.','Check bid security requirement, amount, validity and acceptable format.','Check compulsory pre-bid meeting and/or site-visit requirements.','Review every addendum and clarification issued.','Confirm bidder eligibility, registrations, licences and tax documents.','Prepare all mandatory forms and declarations.','Check signatures, initials, dates, witnesses and company stamp requirements.','Check technical response against every specification.','Check financial proposal / BOQ against the official schedule.','Proof quantities, arithmetic, subtotals, carry-forwards, VAT and final tender amount.','Confirm required validity period and delivery / completion period.','Prepare requested copies, electronic media, envelopes and labels.','Complete a final page-by-page compliance review before submission.']},
    goods:{title:'Goods / Supply Tender Checklist',items:['Confirm exact make, model, product code and specification.','Confirm quantities and whether alternatives/equivalents are permitted.','Obtain manufacturer datasheets and authorisation / reseller evidence where required.','Confirm stock availability and realistic delivery lead time.','Confirm warranty duration, service location and DOA / replacement procedure.','Include all required accessories, cables, software and consumables.','Check freight, insurance, customs, delivery and installation requirements.','Price unit rates and extended totals carefully.','Check VAT treatment and quotation validity.','Confirm samples, catalogues or demonstration requirements.','Proof the final pricing schedule against the official quantities.']},
    services:{title:'Services Tender Checklist',items:['Confirm full scope, locations, frequency and contract period.','Check compulsory site visit / briefing meeting.','Build staffing plan and organisation structure.','Prepare methodology and work plan.','Confirm key personnel qualifications and required CV forms.','Identify equipment, consumables and supervision requirements.','Check service-level, reporting and performance requirements.','Calculate labour, transport, administration and operating costs.','Confirm insurance, statutory and health & safety requirements.','Proof pricing schedule and monthly / annual totals.']},
    works:{title:'Works / Construction Tender Checklist',items:['Confirm contractor category / grading and eligibility.','Attend compulsory site visit and obtain required proof/stamp.','Study drawings, specifications and BOQ together.','Prepare construction methodology and programme.','Confirm key personnel, plant and equipment requirements.','Check temporary works, mobilisation and site-establishment costs.','Price labour, materials, plant, transport and subcontractors.','Check preliminaries, contingency and provisional sums.','Review health, safety, environmental and quality requirements.','Confirm bid security / performance security requirements.','Independently proof every BOQ quantity, rate, amount, subtotal and final tender total.']}
  };
  const library=document.getElementById('checklist-library');
  const order=['general','goods','services','works'];
  library.innerHTML=order.map(key=>{const s=sets[key];return `<article class="checklist-card" data-key="${key}"><span>${key.toUpperCase()}</span><h2>${s.title}</h2><ul>${s.items.slice(0,6).map(i=>`<li>${i}</li>`).join('')}</ul><p>${s.items.length} checks in full download.</p><button class="btn primary download-checklist" data-key="${key}" type="button">Download .txt Checklist</button></article>`}).join('');
  library.addEventListener('click',e=>{
    const btn=e.target.closest('.download-checklist');if(!btn)return;const s=sets[btn.dataset.key];if(!s)return;
    const text=[`MMGC GENERAL TRADING`,`PROCUREMENT DESK — ${s.title}`,'',...s.items.map((x,i)=>`[ ] ${String(i+1).padStart(2,'0')}. ${x}`),'','IMPORTANT: This checklist does not replace the official tender document. The bidder remains responsible for final compliance and for independently proofing BOQ quantities, arithmetic and final tender totals.','',`MMGC General Trading | +266 2233 1570 / +266 5831 1808 | mmgcgeneraltrading@gmail.com`].join('\r\n');
    const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`MMGC-${btn.dataset.key}-tender-checklist.txt`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);
  });
});