(()=>{
  const WA='26658311808';
  const qs=(s)=>document.querySelector(s);
  const qsa=(s)=>[...document.querySelectorAll(s)];
  const clean=(v)=>String(v??'').trim();
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const jobs=()=>[...(Array.isArray(window.MMGC_JOBS)?window.MMGC_JOBS:[]),...(Array.isArray(window.MMGC_SOCIAL_JOBS)?window.MMGC_SOCIAL_JOBS:[])];
  const selectedJob=()=>{const id=new URLSearchParams(location.search).get('id');return id?jobs().find(j=>j.id===id):null};
  const setStatus=(el,msg,type='')=>{if(!el)return;el.textContent=msg;el.hidden=!msg;el.className=`application-alert ${type}`.trim()};
  const setValue=(s,v,{onlyIfBlank=false}={})=>{const el=qs(s);if(!el||v==null)return;if(onlyIfBlank&&clean(el.value))return;el.value=v};
  const toLocalDateTime=(value)=>{if(!value)return '';const d=new Date(value);if(Number.isNaN(d.getTime()))return '';const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};
  const dateForDb=(value)=>{if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString()};

  function detectMethod(job){const text=`${job?.application||''} ${job?.summary||''}`.toLowerCase();if(/hand[\s-]?deliver|deliver.*hand|hard cop|physical submission|submit.*office/.test(text))return 'hand_delivered';if(/email|@/.test(text))return 'email';if(/apply through|online|portal|workday|careers|icims|quantum/.test(text))return 'online';return 'not_specified'}
  const methodLabel=(v)=>({online:'Online application',email:'Email application',hand_delivered:'Hand delivered',not_specified:'Check advert'})[v]||'Check advert';
  function populateJob(job){if(!job)return;qs('#summary-title').textContent=job.title;qs('#summary-text').textContent=job.summary||'Review the official source before submitting.';qs('#summary-meta').innerHTML=[job.employer,job.location,job.deadlineLabel||job.deadline,methodLabel(detectMethod(job))].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');setValue('#job-title-field',job.title);setValue('#employer-field',job.employer);setValue('#source-url-field',job.official||'');setValue('#deadline-field',toLocalDateTime(job.deadline));qs('#application-method').value=detectMethod(job);setValue('#public-notes-field',[job.application,job.requirements?.length?`Requirements: ${job.requirements.join('; ')}`:''].filter(Boolean).join('\n\n'));if(detectMethod(job)==='hand_delivered'){qs('#hand-delivery-required').checked=true;qs('#shop-collection-required').checked=true;qs('#wants-printing').checked=true}}

  function accountKind(){return qs('input[name="account_kind"]:checked')?.value==='company'?'company':'individual'}
  function toggleAccountFields(){const company=accountKind()==='company';qs('#company-account-fields').hidden=!company;qs('#individual-account-fields').hidden=company}
  function authValues(){return {phone:clean(qs('#auth-phone')?.value),pin:clean(qs('#auth-pin')?.value),fullName:clean(qs('#auth-name')?.value),accountKind:accountKind(),companyType:clean(qs('#auth-company-type')?.value),companyName:clean(qs('#auth-company-name')?.value)}}
  async function refreshAuth(){
    const current=qs('#auth-current'),form=qs('#auth-form'),status=qs('#auth-status');
    const session=await window.MMGCPlatform.getSession();
    if(!session?.user){form.hidden=false;current.hidden=true;return}
    form.hidden=true;current.hidden=false;
    const profile=await window.MMGCPlatform.getProfile().catch(()=>null);
    const label=profile?.account_kind==='company'?(profile.company_name||'Company account'):(profile?.full_name||profile?.phone||'Applicant');
    current.innerHTML=`<strong>Signed in as ${esc(label)}</strong><span>${esc(profile?.phone||'')} · Your applications and uploaded PDFs are linked to this account.</span><button class="application-secondary" type="button" id="sign-out">Sign out</button>`;
    setStatus(status,'','');
    if(profile){setValue('#applicant-name-field',profile.full_name||'',{onlyIfBlank:true});setValue('#phone-field',profile.phone||'',{onlyIfBlank:true});setValue('#location-field',profile.location||'',{onlyIfBlank:true});setValue('#auth-name',profile.full_name||'',{onlyIfBlank:true});setValue('#auth-phone',profile.phone||'',{onlyIfBlank:true})}
  }
  function bindAuth(){
    qsa('input[name="account_kind"]').forEach(el=>el.addEventListener('change',toggleAccountFields));
    qs('#auth-card')?.addEventListener('click',async(event)=>{
      const button=event.target.closest('[data-auth-action],#sign-out');if(!button)return;
      const status=qs('#auth-status');button.disabled=true;
      try{
        if(button.id==='sign-out'){await window.MMGCPlatform.signOut();await refreshAuth();setStatus(status,'Signed out.','success');return}
        const v=authValues();if(!v.phone||!v.pin)throw new Error('Enter your phone number and PIN.');
        if(button.dataset.authAction==='signup'){
          if(v.accountKind==='individual'&&!v.fullName)throw new Error('Enter your full name.');
          if(v.accountKind==='company'&&(!v.companyName||!v.companyType))throw new Error('Enter the company name and choose the company type.');
          await window.MMGCPlatform.signUpPhonePin(v);await refreshAuth();setStatus(status,'Account created. You are signed in and can continue.','success');
        }else{await window.MMGCPlatform.signInPhonePin(v);await refreshAuth();setStatus(status,'Signed in.','success')}
      }catch(error){setStatus(status,error.message||'Could not sign in.','error')}finally{button.disabled=false}
    });
  }

  function collectDraftData(){const job=selectedJob();return {job_title:clean(qs('#job-title-field')?.value)||job?.title||'the advertised role',employer:clean(qs('#employer-field')?.value)||job?.employer||'the employer',application_method:qs('#application-method')?.value||detectMethod(job),applicant_name:clean(qs('#applicant-name-field')?.value)||clean(qs('#auth-name')?.value)||'Applicant Name',phone:clean(qs('#phone-field')?.value)||clean(qs('#auth-phone')?.value),email:clean(qs('#applicant-email-field')?.value),location:clean(qs('#location-field')?.value),qualification:clean(qs('#qualification-field')?.value),career_summary:clean(qs('#career-summary-field')?.value),education:clean(qs('#education-field')?.value),experience:clean(qs('#experience-field')?.value),skills:clean(qs('#skills-field')?.value),fit:clean(qs('#fit-field')?.value),current_cv:clean(qs('#current-cv-field')?.value),referees:clean(qs('#referees-field')?.value),requirements:job?.requirements||[],advert_summary:clean(qs('#public-notes-field')?.value)||job?.summary||''}}
  const textValue=(v)=>Array.isArray(v)?v.map(clean).filter(Boolean).join('\n'):clean(v);
  function normalizeExtracted(result){const p=result?.profile||{};return {full_name:textValue(p.full_name),email:textValue(p.email),phone:textValue(p.phone),location:textValue(p.location),highest_qualification:textValue(p.highest_qualification),career_summary:textValue(p.career_summary),education_summary:textValue(p.education_summary),experience_summary:textValue(p.experience_summary),skills:textValue(p.skills),job_fit_summary:textValue(p.job_fit_summary),current_cv_text:textValue(p.current_cv_text),referees:textValue(p.referees),confidence:textValue(result?.confidence||p.confidence),warnings:Array.isArray(result?.warnings)?result.warnings.map(textValue).filter(Boolean):[],missing:Array.isArray(result?.missing)?result.missing.map(textValue).filter(Boolean):[],pages_used:result?.pages_used||[]}}
  function fillExtractedCv(p){[['#applicant-name-field',p.full_name],['#phone-field',p.phone],['#applicant-email-field',p.email],['#location-field',p.location],['#qualification-field',p.highest_qualification],['#career-summary-field',p.career_summary],['#education-field',p.education_summary],['#experience-field',p.experience_summary],['#skills-field',p.skills],['#fit-field',p.job_fit_summary],['#current-cv-field',p.current_cv_text],['#referees-field',p.referees]].forEach(([s,v])=>{if(clean(v))setValue(s,v,{onlyIfBlank:true})});if(p.full_name)setValue('#auth-name',p.full_name,{onlyIfBlank:true});if(p.phone)setValue('#auth-phone',p.phone,{onlyIfBlank:true})}
  function renderCvExtractPreview(p){const preview=qs('#cv-extract-preview');if(!preview)return;const items=[['Name',p.full_name],['Phone',p.phone],['Email',p.email],['Qualification',p.highest_qualification],['Relevant skills',p.skills],['Experience',p.experience_summary],['Education',p.education_summary]].filter(([,v])=>clean(v));const detail=items.length?`<div class="cv-extract-grid">${items.map(([l,v])=>`<div class="cv-extract-item"><b>${esc(l)}</b><span>${esc(v)}</span></div>`).join('')}</div>`:'<p class="cv-extract-note">The PDF was read, but only a small amount of structured CV information was found. You can still submit it for MMGC staff review.</p>';const notes=[p.pages_used?.length?`<strong>CV pages used:</strong> ${esc(p.pages_used.join(', '))}`:'',p.confidence?`<strong>Confidence:</strong> ${esc(p.confidence)}`:'',p.missing?.length?`<strong>Still check:</strong> ${esc(p.missing.join(', '))}`:'',p.warnings?.length?`<strong>Reader note:</strong> ${esc(p.warnings.join(' '))}`:''].filter(Boolean).join('<br>');preview.innerHTML=`<h3>Useful CV details found</h3>${detail}${notes?`<p class="cv-extract-note">${notes}</p>`:''}`;preview.hidden=false}
  async function extractCvAndFill(){
    const status=qs('#cv-extract-status'),button=qs('#extract-cv-fill'),file=qs('#cv-files')?.files?.[0];
    if(!file){setStatus(status,'Choose a PDF first.','error');return}
    if(!(file.type==='application/pdf'||/\.pdf$/i.test(file.name))){setStatus(status,'Please choose a PDF file.','error');return}
    button.disabled=true;setStatus(status,'Reading the PDF in your browser…','');
    try{
      const d=collectDraftData();
      const result=await window.MMGCFreeCVExtractor.extract(file,{title:d.job_title,employer:d.employer,advert_summary:d.advert_summary,requirements:d.requirements},{onProgress:(m)=>setStatus(status,m,'')});
      const p=normalizeExtracted(result);fillExtractedCv(p);renderCvExtractPreview(p);qs('#cv-details-panel').open=true;setStatus(status,'Autofill complete. The site used CV-looking pages and ignored likely letters/certificates. Check names, dates and numbers before submitting.','success');
    }catch(error){setStatus(status,`CV AI extraction is temporarily unavailable. The website tried free text extraction first. ${error.message||''} You can still submit the PDF and MMGC staff can review it.`,'error')}finally{button.disabled=false}
  }

  const listLines=(text)=>clean(text).split(/\n|;|,/).map(clean).filter(Boolean).slice(0,10);
  function localDraft(data){const skills=listLines(data.skills),req=(data.requirements||[]).slice(0,4).join('; ');const cv=[data.applicant_name.toUpperCase(),[data.phone,data.email,data.location].filter(Boolean).join(' | '),'','CAREER PROFILE',data.career_summary||`Applicant targeting ${data.job_title} at ${data.employer}.`,'','TARGET ROLE',`${data.job_title} — ${data.employer}`,'','RELEVANT SKILLS',...(skills.length?skills.map(s=>`• ${s}`):['• Add only skills supported by the applicant’s CV']),'','EDUCATION AND TRAINING',data.education||data.qualification||'Add education and training from the CV.','','WORK EXPERIENCE',data.experience||'Add verified work experience from the CV.','','JOB MATCH',data.fit||`Tailor this section to ${data.job_title}.${req?` Advert areas to address: ${req}`:''}`,'','REFEREES',data.referees||'Available on request.'].join('\n');const letter=[new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'}),'','The Hiring Manager',data.employer,'',`RE: APPLICATION FOR ${data.job_title.toUpperCase()}`,'',`I wish to apply for the position of ${data.job_title} at ${data.employer}.`,data.career_summary?`\n${data.career_summary}`:'',data.fit?`\nMy background is relevant to this role because ${data.fit}`:'','',`I have attached my CV and supporting documents for your consideration.`,'','Yours faithfully,',data.applicant_name,data.phone?`Tel: ${data.phone}`:'',data.email?`Email: ${data.email}`:''].filter(x=>x!==null).join('\n');return {cv,letter,mode:'website_draft'}}
  async function createDrafts(){const status=qs('#draft-status'),output=qs('#draft-output'),data=collectDraftData();if(!data.career_summary&&!data.experience&&!data.skills&&!data.current_cv){setStatus(status,'Read the PDF first or add some CV details.','error');return}qs('#generate-drafts').disabled=true;setStatus(status,'Preparing editable drafts…','');let drafts;try{const response=await fetch(location.hostname.endsWith('vercel.app')?'/api/job-application-ai':'https://mmgcgeneraltrading-github-io.vercel.app/api/job-application-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'draft',application:data})});const result=await response.json().catch(()=>({}));if(!response.ok||!result.cv||!result.letter)throw new Error('AI unavailable');drafts={cv:result.cv,letter:result.letter,mode:'ai_assisted'};setStatus(status,'Enhanced drafts are ready. Review before using them.','success')}catch{drafts=localDraft(data);setStatus(status,'Drafts are ready using the free built-in template. MMGC staff can improve them further.','success')}finally{qs('#generate-drafts').disabled=false}qs('#cv-draft').value=drafts.cv;qs('#letter-draft').value=drafts.letter;output.hidden=false;output.dataset.mode=drafts.mode}

  function guessDocType(file,preferred){if(preferred)return preferred;const name=file.name.toLowerCase();if(name.includes('cv')||name.includes('resume'))return 'cv';if(name.includes('cert'))return 'certificate';if(name.includes('id'))return 'id_copy';if(name.includes('letter'))return 'application_letter';if(name.includes('post')||name.includes('advert'))return 'job_post';return 'other'}
  function collectFiles(){const cv=[...(qs('#cv-files')?.files||[])].map(file=>({file,type:'cv'}));const supporting=[...(qs('#supporting-files')?.files||[])].map(file=>({file,type:guessDocType(file)}));return [...cv,...supporting]}
  function serviceLevel(){if(qs('#wants-printing')?.checked&&!qs('#wants-new-cv')?.checked&&!qs('#wants-cv-tailoring')?.checked&&!qs('#wants-letter')?.checked)return 'print_only';if(qs('#wants-new-cv')?.checked||qs('#wants-cv-tailoring')?.checked||qs('#wants-letter')?.checked||qs('#wants-printing')?.checked)return 'mmgc_assisted';return 'self_service'}
  async function submitApplication(event){
    event.preventDefault();const status=qs('#submit-status'),button=qs('#submit-application');
    if(!qs('#privacy-consent')?.checked){setStatus(status,'Please accept the privacy consent before submitting.','error');return}
    const session=await window.MMGCPlatform.getSession();if(!session?.user){setStatus(status,'Please create an account or sign in first.','error');qs('#auth-card')?.scrollIntoView({behavior:'smooth',block:'start'});return}
    const data=collectDraftData();if(!data.job_title||!data.applicant_name||!data.phone){setStatus(status,'Job title, applicant name and phone number are required.','error');return}
    button.disabled=true;setStatus(status,'Saving application…','');
    try{
      const profile=await window.MMGCPlatform.getProfile().catch(()=>null);const aKind=profile?.account_kind||accountKind();
      await window.MMGCPlatform.upsertProfile({fullName:data.applicant_name,phone:data.phone,location:data.location,profileType:aKind==='company'?'customer':'applicant',accountKind:aKind,companyType:profile?.company_type||clean(qs('#auth-company-type')?.value)||null,companyName:profile?.company_name||clean(qs('#auth-company-name')?.value)});
      const application=await window.MMGCPlatform.createApplication({job_post_external_id:selectedJob()?.id||null,job_title:data.job_title,employer:data.employer,source_url:clean(qs('#source-url-field')?.value),deadline:dateForDb(qs('#deadline-field')?.value),application_method:data.application_method,applicant_name:data.applicant_name,applicant_email:data.email||null,phone:data.phone,location:data.location,highest_qualification:data.qualification,career_summary:data.career_summary,education_summary:data.education,experience_summary:data.experience,skills:data.skills,current_cv_text:data.current_cv,why_right_fit:data.fit,referees:data.referees,wants_new_cv:qs('#wants-new-cv')?.checked||false,wants_cv_tailoring:qs('#wants-cv-tailoring')?.checked||false,wants_application_letter:qs('#wants-letter')?.checked||false,wants_printing:qs('#wants-printing')?.checked||false,hand_delivery_required:qs('#hand-delivery-required')?.checked||data.application_method==='hand_delivered',shop_collection_required:qs('#shop-collection-required')?.checked||false,service_level:serviceLevel(),collection_status:(qs('#shop-collection-required')?.checked||data.application_method==='hand_delivered')?'pending':'not_required',public_notes:clean(qs('#public-notes-field')?.value),privacy_consent:true});
      const files=collectFiles();for(let i=0;i<files.length;i++){setStatus(status,`Uploading PDF ${i+1} of ${files.length}…`,'');await window.MMGCPlatform.uploadApplicationFile(files[i].file,application.id,files[i].type)}
      const cvDraft=clean(qs('#cv-draft')?.value),letterDraft=clean(qs('#letter-draft')?.value),mode=qs('#draft-output')?.dataset.mode||'website_draft';if(cvDraft)await window.MMGCPlatform.saveGeneratedDocument(application.id,'cv',`${application.reference_no} CV draft`,cvDraft,mode,qs('#wants-printing')?.checked||false);if(letterDraft)await window.MMGCPlatform.saveGeneratedDocument(application.id,'application_letter',`${application.reference_no} application letter`,letterDraft,mode,qs('#wants-printing')?.checked||false);
      const collection=application.shop_collection_required||application.hand_delivery_required?' MMGC will mark the file ready when hard copies can be collected.':' You can track progress from My Applications.';const message=`Hello MMGC, my job application support reference is ${application.reference_no}. Job: ${data.job_title}${data.employer?` at ${data.employer}`:''}.`;
      qs('#success-ref').textContent=application.reference_no;qs('#success-message').textContent=`Your application has been saved.${collection}`;qs('#success-whatsapp').href=`https://wa.me/${WA}?text=${encodeURIComponent(message)}`;qs('#success-panel').hidden=false;setStatus(status,'Application saved successfully.','success');qs('#success-panel')?.scrollIntoView({behavior:'smooth',block:'start'});
    }catch(error){setStatus(status,error.message||'The application could not be submitted. Please try again.','error')}finally{button.disabled=false}
  }

  document.addEventListener('DOMContentLoaded',async()=>{
    const authError=window.MMGCPlatform.initAuthFromUrl();if(authError)setStatus(qs('#auth-status'),authError,'error');
    populateJob(selectedJob());toggleAccountFields();bindAuth();await refreshAuth();
    qs('#extract-cv-fill')?.addEventListener('click',extractCvAndFill);qs('#generate-drafts')?.addEventListener('click',createDrafts);qs('#application-form')?.addEventListener('submit',submitApplication);
    qs('#application-method')?.addEventListener('change',()=>{if(qs('#application-method')?.value==='hand_delivered'){qs('#hand-delivery-required').checked=true;qs('#shop-collection-required').checked=true;qs('#wants-printing').checked=true}});
  });
})();
