window.MMGC_TENDERS = [
{
id:'roadfund-promotional',issuerKey:'roadfund',issuer:'Road Fund Lesotho',title:'Supply & Delivery of 2027 Promotional Materials',ref:'',type:'major',categories:['goods','printing'],summary:'Supply and delivery of 2027 promotional materials. Road Fund has published Addendum 1.',simple:'Road Fund is procuring branded promotional materials. Use the latest tender document together with Addendum 1 for final specifications, quantities and submission requirements.',deadline:'2026-09-11T23:59:59+02:00',deadlineLabel:'11 September 2026 · exact time to verify',published:'',documentFee:{state:'unknown',label:'Check latest tender document'},bidSecurity:{state:'unknown',label:'Check latest tender document'},siteVisit:{state:'unknown',label:'No site visit confirmed by MMGC — verify'},preBid:{state:'unknown',label:'Verify latest notice'},official:'https://www.roadfund.org.ls/tenders/',verification:'official',verifiedAt:'10 September 2026',addenda:['Addendum 1 published by Road Fund'],lots:[{title:'Promotional Materials',text:'Use the latest Road Fund tender document and Addendum 1 for exact items, quantities, branding and delivery requirements.'}],checklist:['Download the tender and Addendum 1.','Confirm exact closing time.','Check samples/branding requirements.','Confirm bid security and mandatory forms.','Price goods, branding, packaging and delivery.']
},
{
id:'lhda-water',issuerKey:'lhda',issuer:'Lesotho Highlands Development Authority (LHDA)',title:'RFQ for Water Samples',ref:'',type:'rfq',categories:['services'],summary:'Current LHDA request for quotation relating to water samples.',simple:'Review the full RFQ and the current bidder clarification before pricing. Confirm sampling scope, standards, locations, quantities and laboratory requirements.',deadline:'2026-09-15T12:00:00+02:00',deadlineLabel:'15 September 2026 · 12:00',published:'',documentFee:{state:'public',label:'Download from LHDA current tenders'},bidSecurity:{state:'unknown',label:'Verify RFQ'},siteVisit:{state:'unknown',label:'Verify RFQ'},preBid:{state:'unknown',label:'Verify RFQ'},official:'https://www.lhda.org.ls/procurement/currentTenders',verification:'official',verifiedAt:'10 September 2026',addenda:['C1404 response to bidders request for clarification listed by LHDA'],lots:[{title:'Water Samples',text:'Confirm the complete water-sampling/testing scope in the official RFQ and latest clarification.'}],checklist:['Download RFQ and latest clarification.','Confirm laboratory/technical accreditation requirements.','Check sample quantities and locations.','Confirm submission method.','Proof final quotation.']
},
{
id:'rsl-ict-equipment',issuerKey:'rsl',issuer:'Revenue Services Lesotho (RSL)',title:'Supply and Delivery of ICT Equipment',ref:'',type:'major',categories:['goods','ict'],summary:'RSL procurement opportunity for ICT equipment.',simple:'RSL is procuring ICT equipment. Obtain the detailed RFP and confirm specifications, quantities, mandatory documents and delivery requirements before costing.',deadline:'2026-09-15T23:59:59+02:00',deadlineLabel:'15 September 2026 · exact time to verify',published:'',documentFee:{state:'unknown',label:'RFP available on request — verify fee'},bidSecurity:{state:'unknown',label:'Check RFP'},siteVisit:{state:'unknown',label:'Check RFP'},preBid:{state:'unknown',label:'Check RFP'},official:'https://www.rsl.org.ls/opportunities-jobs-tenders',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'ICT Equipment',text:'Use the RSL RFP for exact equipment, specifications, quantities and warranty requirements.'}],eligibility:['Valid Tax Clearance Certificate.','Company registration licence.','Shareholding certificate.','Recent annual financial statements.','Relevant track record/licensing as required by RSL.'],checklist:['Request/download the detailed RFP.','Confirm exact closing time.','Check mandatory certifications and specifications.','Confirm bid security.','Price delivery and warranty.']
},
{
id:'lhda-computers',issuerKey:'lhda',issuer:'Lesotho Highlands Development Authority (LHDA)',title:'RFQ for Purchasing of Computers / HP Laptops',ref:'RFQ 001-2026',type:'rfq',categories:['goods','ict'],summary:'Supply and delivery of HP EliteBook 6 G-series laptops in two lots with required accessories.',simple:'LHDA is requesting HP business laptops. Bidders must carefully match the required configuration, accessories, warranty and dealer requirements.',deadline:'2026-09-17T12:00:00+02:00',deadlineLabel:'17 September 2026 · 12:00',published:'',documentFee:{state:'public',label:'Free download from LHDA; M1,000 for physical tender document'},bidSecurity:{state:'unknown',label:'Verify RFQ'},siteVisit:{state:'none',label:'No compulsory site visit identified'},preBid:{state:'none',label:'No pre-bid meeting identified'},official:'https://www.lhda.org.ls/procurement/currentTenders',verification:'double',verifiedAt:'10 September 2026',lots:[{title:'Lot 1 — 14-inch HP EliteBook 6 G-series',text:'Quantity 22; 32GB RAM, 1TB SSD, Windows 11 Pro and specified accessories. Confirm exact model/processor in RFQ.'},{title:'Lot 2 — 16-inch HP EliteBook 6 G-series',text:'Quantity 10; 32GB RAM, 1TB SSD, Windows 11 Pro and specified accessories. Confirm exact model/processor in RFQ.'}],eligibility:['Competent HP accredited dealer.','Meet all technical and documentary requirements in the RFQ.'],checklist:['Confirm HP accreditation evidence.','Confirm exact laptop models and processor requirements.','Include all required accessories.','Confirm warranty duration.','Prepare original/copies exactly as instructed.','Submit before 12:00 on 17 September.']
},
{
id:'finance-ifmis-project-manager',issuerKey:'finance',issuer:'Ministry of Finance & Development Planning',title:'IFMIS Upgrade Project Manager',ref:'',type:'major',categories:['services','consulting'],summary:'Project management procurement connected to the IFMIS upgrade.',simple:'A professional-services opportunity. Review the TOR for qualifications, experience, deliverables, duration and proposal requirements.',deadline:'2026-09-15T23:59:59+02:00',deadlineLabel:'15 September 2026 · exact time to verify',published:'14 August 2026',documentFee:{state:'unknown',label:'Check Ministry notice'},bidSecurity:{state:'unknown',label:'Check TOR / notice'},siteVisit:{state:'none',label:'No site visit identified by MMGC'},preBid:{state:'unknown',label:'Verify notice'},official:'https://finance.gov.ls/tenders',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'Project Manager',text:'Use the official TOR for scope, qualifications, deliverables and contract period.'}],checklist:['Download TOR.','Confirm individual/firm eligibility.','Match CV/experience to evaluation criteria.','Confirm proposal format and deadline time.']
},
{
id:'finance-telematics',issuerKey:'finance',issuer:'Ministry of Finance & Development Planning',title:'Telematics Tender',ref:'',type:'major',categories:['services','ict'],summary:'Technology/services procurement listed by the Ministry of Finance.',simple:'Obtain and study the full telematics tender for technical requirements, locations, contract period, implementation obligations and bidder qualifications.',deadline:'2026-09-22T23:59:59+02:00',deadlineLabel:'22 September 2026 · exact time to verify',published:'14 August 2026',documentFee:{state:'unknown',label:'Check Ministry tender notice'},bidSecurity:{state:'unknown',label:'Check bidding document'},siteVisit:{state:'unknown',label:'Confirm in bidding document'},preBid:{state:'unknown',label:'Confirm in bidding document'},official:'https://finance.gov.ls/tenders',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'Telematics Requirement',text:'Use the official bidding document for complete system/service scope, quantities, locations and contract conditions.'}],checklist:['Obtain complete bidding document.','Check technical and experience requirements.','Confirm bid security.','Check meetings/site visits.','Confirm exact submission time.']
},
{
id:'gov-ltv-programmes',issuerKey:'government',issuer:'Ministry of Information, Communications, Science, Technology and Innovation (MICSTI)',title:'Supply and Delivery of LTV Programmes',ref:'',type:'major',categories:['goods','services','media'],summary:'Procurement for supply and delivery of Lesotho Television programmes.',simple:'MICSTI is procuring LTV programmes. The detailed notice requires a Bid Securing Declaration and provides for a pre-bid meeting. Verify the exact pre-bid date in the issued bidding document.',deadline:'2026-09-21T10:00:00+02:00',deadlineLabel:'21 September 2026 · 10:00',published:'17 August 2026',documentFee:{state:'unknown',label:'Payment by bank transfer — confirm amount in bidding document'},bidSecurity:{state:'declaration',label:'Bid Securing Declaration · valid until 4 March 2027'},siteVisit:{state:'none',label:'No compulsory site visit identified'},preBid:{state:'required',label:'Pre-bid meeting at National Library premises — verify date in bidding document'},official:'https://www.gov.ls/documents/tenders/',verification:'double',verifiedAt:'10 September 2026',lots:[{title:'LTV Programmes',text:'Use the issued bidding document for programme categories, quantities/content requirements and evaluation criteria.'}],checklist:['Confirm pre-bid meeting date.','Prepare Bid Securing Declaration.','Confirm tender document fee.','Submit before 10:00 on 21 September.','Bid opening listed for 10:30.']
},
{
id:'gov-production-equipment',issuerKey:'government',issuer:'Ministry of Information, Communications, Science, Technology and Innovation (MICSTI)',title:'LTV Supply & Delivery of Production Equipment',ref:'',type:'major',categories:['goods','ict','media'],summary:'Supply and delivery of production/broadcast equipment.',simple:'A specialist broadcast-equipment supply tender. Check every required specification, quantity, accessory, warranty and delivery condition before sourcing.',deadline:'2026-09-21T10:00:00+02:00',deadlineLabel:'21 September 2026 · 10:00',published:'17 August 2026',documentFee:{state:'unknown',label:'Payment by bank transfer — confirm amount'},bidSecurity:{state:'declaration',label:'Bid Securing Declaration · valid until 4 March 2027'},siteVisit:{state:'none',label:'No site visit identified'},preBid:{state:'none',label:'No pre-bid meeting stated'},official:'https://www.gov.ls/documents/tenders/',verification:'double',verifiedAt:'10 September 2026',lots:[{title:'Production Equipment',text:'Refer to official bidding document for complete item list, quantities and technical specifications.'}],checklist:['Download bidding document.','Prepare Bid Securing Declaration.','Identify all equipment/specifications.','Price accessories, warranty and delivery.','Submit before 10:00 on 21 September.']
},
{
id:'gov-vision-mixer',issuerKey:'government',issuer:'Ministry of Information, Communications, Science, Technology and Innovation (MICSTI)',title:'Production Studio Vision Mixer and Accessories',ref:'',type:'major',categories:['goods','ict','media'],summary:'Supply, installation and configuration of production studio vision mixer and accessories.',simple:'A specialist broadcast-system tender. Technical compatibility, installation, configuration, accessories and warranty must be checked against the bidding document.',deadline:'2026-09-21T10:00:00+02:00',deadlineLabel:'21 September 2026 · 10:00',published:'17 August 2026',documentFee:{state:'unknown',label:'Payment by bank transfer — confirm amount'},bidSecurity:{state:'declaration',label:'Bid Securing Declaration · valid until 4 March 2027'},siteVisit:{state:'none',label:'No compulsory site visit identified'},preBid:{state:'required',label:'Pre-bid meeting stated — verify exact date/venue in bidding document'},official:'https://www.gov.ls/documents/tenders/',verification:'double',verifiedAt:'10 September 2026',lots:[{title:'Vision Mixer & Accessories',text:'Use official specifications for mixer, accessories, installation and configuration requirements.'}],checklist:['Confirm pre-bid meeting details.','Prepare Bid Securing Declaration.','Check installation/configuration obligations.','Confirm compatible accessories and warranty.','Submit before 10:00 on 21 September.']
},
{
id:'gov-cleaning',issuerKey:'government',issuer:'Ministry of Information, Communications, Science, Technology and Innovation (MICSTI)',title:'Provision of Cleaning Services for National Library',ref:'',type:'major',categories:['services','cleaning'],summary:'Cleaning-services tender for the National Library.',simple:'This tender includes a mandatory site visit which took place on 4 September 2026. A bidder should confirm whether missing that visit affects eligibility before doing further bid work.',deadline:'2026-09-28T10:00:00+02:00',deadlineLabel:'28 September 2026 · 10:00',published:'24 August 2026',documentFee:{state:'unknown',label:'Payment by bank transfer — confirm amount'},bidSecurity:{state:'declaration',label:'Bid Securing Declaration · valid until 16 March 2027'},siteVisit:{state:'passed',label:'MANDATORY site visit · 4 September 2026 (passed)'},preBid:{state:'none',label:'Mandatory site visit applies instead'},official:'https://www.gov.ls/documents/tenders/',verification:'double',verifiedAt:'10 September 2026',lots:[{title:'National Library Cleaning Services',text:'Study scope for premises, staffing, cleaning frequency, consumables, equipment and contract duration.'}],eligibility:['Attendance at the mandatory site visit may be an eligibility condition — confirm with MICSTI before preparing a bid.'],checklist:['Confirm site-visit eligibility before proceeding.','Prepare Bid Securing Declaration.','Calculate staffing, supervision, equipment and consumables.','Submit before 10:00 on 28 September.']
},
{
id:'efu-schools-batch3',issuerKey:'government',issuer:'Ministry of Education and Training / Education Facilities Unit (EFU)',title:'Construction of Classrooms, Latrines & Associated Site Works at Primary Schools — Batch 3',ref:'',type:'major',categories:['works','construction'],summary:'Multi-package school construction tender covering classrooms, latrines and associated site works.',simple:'This is a multi-lot construction procurement. Site visits are compulsory for every lot a bidder intends to bid for, and the signed Site Visit Confirmation Form must accompany the bid.',deadline:'2026-09-29T10:00:00+02:00',deadlineLabel:'29 September 2026 · 10:00',published:'',documentFee:{state:'unknown',label:'Check bidding document'},bidSecurity:{state:'required',label:'Bank Guarantee: M5,000–M40,000 depending on scope'},siteVisit:{state:'required',label:'COMPULSORY for every lot · weekdays 08:30–16:00'},preBid:{state:'passed',label:'Pre-bid meeting held 18 August 2026 · 10:00'},official:'https://www.gov.ls/documents/tenders/',verification:'cross',verifiedAt:'10 September 2026',lots:[{title:'Packages / Lots',text:'Six packages are referenced. Obtain the complete RFB for school names, lot breakdown and BOQs.'}],checklist:['Visit every lot being bid and obtain signed confirmation.','Match bid security to the scope: M5,000 / M10,000 / M20,000 / M30,000 / M40,000 as applicable.','Complete BOQs and construction programme.','Submit before 10:00 on 29 September.','Packages 1–3 opening 29 Sep 10:30; Packages 4–6 opening 30 Sep 09:00.']
},
{
id:'roll-gardening-tools',issuerKey:'roll',issuer:'Regeneration of Landscapes and Livelihoods (ROLL)',title:'Procurement and Distribution of Gardening Tools',ref:'LSO-2000002340-0232-G-NCB',type:'major',categories:['goods','agriculture'],summary:'Supply and distribution of gardening tools under the ROLL project.',simple:'ROLL is procuring gardening tools. Download the bidding documents and price the exact tools, quantities, delivery/distribution locations and required standards.',deadline:'2026-10-06T23:59:59+02:00',deadlineLabel:'6 October 2026 · exact time to verify',published:'28 August 2026',documentFee:{state:'public',label:'Bidding documents available from ROLL tender page'},bidSecurity:{state:'unknown',label:'Check bidding document'},siteVisit:{state:'unknown',label:'Check bidding document'},preBid:{state:'unknown',label:'Check bidding document'},official:'https://rollproject.gov.ls/tenders',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'Gardening Tools',text:'Use the bidding documents for exact tool specifications, quantities and distribution requirements.'}],checklist:['Get bidding documents.','Confirm bid security.','Price exact specifications and quantities.','Include distribution/delivery costs.','Confirm closing time.']
},
{
id:'roll-food-processing',issuerKey:'roll',issuer:'Regeneration of Landscapes and Livelihoods (ROLL)',title:'Supply & Delivery of Food Processing Equipment (Can Fruits)',ref:'LSO-2000002340-0230-G-NCB',type:'major',categories:['goods','equipment','agriculture'],summary:'Supply and delivery of food-processing equipment for canning fruits.',simple:'A specialist equipment supply opportunity. Confirm capacities, technical specifications, installation/training requirements and delivery destinations before pricing.',deadline:'2026-10-05T23:59:59+02:00',deadlineLabel:'5 October 2026 · exact time to verify',published:'21 August 2026',documentFee:{state:'public',label:'Bidding documents available from ROLL tender page'},bidSecurity:{state:'unknown',label:'Check bidding document'},siteVisit:{state:'unknown',label:'Check bidding document'},preBid:{state:'unknown',label:'Check bidding document'},official:'https://rollproject.gov.ls/tenders',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'Food Processing Equipment',text:'Use the bidding documents for exact machinery, capacities, quantities and ancillary requirements.'}],checklist:['Get bidding documents.','Confirm equipment specifications/capacities.','Check installation, commissioning and training.','Confirm warranty and bid security.','Price freight/delivery.']
},
{
id:'rsl-structural-engineer-academy',issuerKey:'rsl',issuer:'Revenue Services Lesotho (RSL)',title:'Provision of Structural Engineer – RSL Academy',ref:'',type:'major',categories:['services','consulting','engineering'],summary:'Professional structural engineering services for the RSL Academy.',simple:'RSL is seeking structural engineering services. Obtain the detailed RFP for scope, deliverables, professional registration and experience requirements.',deadline:'2026-10-08T23:59:59+02:00',deadlineLabel:'8 October 2026 · exact time to verify',published:'',documentFee:{state:'unknown',label:'Check RSL notice'},bidSecurity:{state:'unknown',label:'Check RFP'},siteVisit:{state:'unknown',label:'Check RFP'},preBid:{state:'unknown',label:'Check RFP'},official:'https://www.rsl.org.ls/opportunities-jobs-tenders',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'Structural Engineering Services',text:'Use the RSL RFP for exact scope, inspections/designs, deliverables and professional requirements.'}],checklist:['Obtain detailed RFP.','Confirm professional registration requirements.','Prepare relevant project experience.','Confirm site visit/briefing requirements.','Confirm closing time.']
},
{
id:'trade-supplier-database-2026',issuerKey:'government',issuer:'Ministry of Trade, Industry and Business Development',title:'EOI — Supplier Database for Goods, Works and Services',ref:'',type:'major',categories:['supplier','goods','works','services'],summary:'Expression of Interest to pre-qualify suppliers, consultants and contractors for the 2026/27 and 2027/28 financial years.',simple:'This is supplier registration/pre-qualification rather than a single purchase. Suitable businesses should submit a strong business profile and all requested legal/compliance evidence for relevant categories.',deadline:null,deadlineLabel:'Confirm submission deadline in full EOI',published:'3 September 2026',documentFee:{state:'unknown',label:'Check full EOI'},bidSecurity:{state:'none',label:'No bid security identified in public summary'},siteVisit:{state:'none',label:'Not applicable'},preBid:{state:'none',label:'Not applicable'},official:'https://www.gov.ls/download-category/opportunities/',verification:'cross',verifiedAt:'10 September 2026',lots:[{title:'Supplier Categories',text:'Goods, works, services, consultants and contractors for future Ministry procurement during 2026/27 and 2027/28.'}],checklist:['Obtain full EOI.','Choose all relevant categories.','Prepare company profile and experience evidence.','Attach valid legal/tax/licensing documents.','Confirm submission deadline and method.']
},
{
id:'lec-prequalification',issuerKey:'lec',issuer:'Lesotho Electricity Company (LEC)',title:'Advert for Pre-Qualification',ref:'',type:'major',categories:['services','works','goods'],summary:'New LEC pre-qualification notice published 10 September 2026.',simple:'This is a pre-qualification process. Applicants should focus on the categories, eligibility, licences, capacity, experience and evidence required by LEC rather than price alone.',deadline:null,deadlineLabel:'Confirm from LEC tender PDF',published:'10 September 2026',documentFee:{state:'unknown',label:'Check LEC notice'},bidSecurity:{state:'unknown',label:'Do not assume — verify notice'},siteVisit:{state:'unknown',label:'Check LEC notice'},preBid:{state:'unknown',label:'Check LEC notice'},official:'https://lec.co.ls/tenders/',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'Pre-Qualification Categories',text:'Open the LEC tender PDF for exact categories and documentary requirements.'}],checklist:['Download 10 Sep pre-qualification advert.','Choose correct categories.','Prepare licences and experience evidence.','Check financial/capacity requirements.','Confirm closing date/time.']
},
{
id:'lec-strategic-goods',issuerKey:'lec',issuer:'Lesotho Electricity Company (LEC)',title:'Supply and Delivery of Strategic Goods',ref:'',type:'major',categories:['goods','electrical'],summary:'LEC supply tender published 4 September 2026 for strategic goods.',simple:'A current LEC goods tender. Download the official advert/document for exact electrical/strategic items, quantities, specifications, eligibility and closing date.',deadline:null,deadlineLabel:'Confirm from LEC tender PDF',published:'4 September 2026',documentFee:{state:'unknown',label:'Check LEC notice'},bidSecurity:{state:'unknown',label:'Check LEC notice'},siteVisit:{state:'unknown',label:'Check LEC notice'},preBid:{state:'unknown',label:'Check LEC notice'},official:'https://lec.co.ls/tenders/',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'Strategic Goods',text:'Use the official LEC tender PDF for exact goods, quantities and specifications.'}],checklist:['Download official advert.','Confirm closing date/time.','Check item specifications and quantities.','Confirm bid security and mandatory documents.']
},
{
id:'lec-fleet-management',issuerKey:'lec',issuer:'Lesotho Electricity Company (LEC)',title:'Fleet Management Services',ref:'',type:'major',categories:['services','fleet'],summary:'LEC tender for fleet management services published 28 August 2026.',simple:'A fleet-management services procurement. Download the LEC notice to confirm fleet size, service scope, technology, maintenance/reporting requirements and closing date.',deadline:null,deadlineLabel:'Confirm from LEC tender PDF',published:'28 August 2026',documentFee:{state:'unknown',label:'Check LEC notice'},bidSecurity:{state:'unknown',label:'Check LEC notice'},siteVisit:{state:'unknown',label:'Check LEC notice'},preBid:{state:'unknown',label:'Check LEC notice'},official:'https://lec.co.ls/tenders/',verification:'official',verifiedAt:'10 September 2026',lots:[{title:'Fleet Management Services',text:'Use the official LEC tender document for complete service scope and fleet requirements.'}],checklist:['Download official advert.','Confirm closing date/time.','Review fleet/service requirements.','Check technical platform and reporting requirements.','Confirm mandatory documents.']
}
];
window.MMGC_ISSUERS={finance:{name:'Ministry of Finance & Development Planning',short:'Ministry of Finance',url:'https://finance.gov.ls/tenders'},roadfund:{name:'Road Fund Lesotho',short:'Road Fund',url:'https://www.roadfund.org.ls/tenders/'},lhda:{name:'Lesotho Highlands Development Authority (LHDA)',short:'LHDA',url:'https://www.lhda.org.ls/procurement/currentTenders'},rsl:{name:'Revenue Services Lesotho (RSL)',short:'RSL',url:'https://www.rsl.org.ls/opportunities-jobs-tenders'},government:{name:'Government of Lesotho',short:'Government of Lesotho',url:'https://www.gov.ls/documents/tenders/'},lec:{name:'Lesotho Electricity Company (LEC)',short:'LEC',url:'https://lec.co.ls/tenders/'},roll:{name:'Regeneration of Landscapes and Livelihoods (ROLL)',short:'ROLL',url:'https://rollproject.gov.ls/tenders'}};