document.addEventListener('DOMContentLoaded',()=>{
const tenders=Array.isArray(window.MMGC_TENDERS)?window.MMGC_TENDERS:[],now=new Date(),dayMs=86400000,twoDaysMs=2*dayMs,container=document.getElementById('tender-cards'),alerts=document.getElementById('procurement-alerts'),search=document.getElementById('tender-search'),filterButtons=[...document.querySelectorAll('.filter-chip')],countEl=document.getElementById('open-count'),empty=document.getElementById('no-open-tenders'),navToggle=document.getElementById('nav-toggle');let activeFilter='all';
const esc=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const expired=t=>t.deadline&&new Date(t.deadline)<now,remaining=t=>t.deadline?new Date(t.deadline)-now:null;
const daysLabel=t=>{const ms=remaining(t);if(ms===null)return'Deadline to verify';if(ms<0)return'Closed';const h=Math.ceil(ms/3600000);if(h<=24)return h<=1?'Closes within 1 hour':`${h} hours left`;const d=Math.ceil(ms/dayMs);return`${d} day${d===1?'':'s'} left`};
const typeLabel=t=>({rfq:'RFQ',major:'TENDER / EOI',threshold:'THRESHOLD'}[t]||'CURRENT NOTICE');
const verify=t=>t.verification==='double'?'✓ Double verified':t.verification==='official'?'✓ Official source':'Cross-checked';
const visitUrl=t=>`https://wa.me/26658311808?text=${encodeURIComponent(`Hello MMGC, I need site-visit attendance/support for: ${t.title} (${t.issuer}). Please confirm whether an authorised representative may attend and what documents are required.`)}`;
const card=t=>{const ms=remaining(t),urgent=ms!==null&&ms>=0&&ms<=twoDaysMs,cats=(t.categories||[]).map(c=>`<a href="category.html?category=${encodeURIComponent(c)}">${esc(c.toUpperCase())}</a>`).join(''),detail=`tender-details.html?id=${encodeURIComponent(t.id)}`,share=encodeURIComponent(`${t.title}\n${t.issuer}\nDeadline: ${t.deadlineLabel||'Confirm with issuer'}\nMMGC summary: ${location.origin}/${detail}`),possible=(t.siteVisit?.state||'unknown')!=='none',addenda=(t.addenda||[]).length?`<div class="tender-addenda"><b>ADDENDA / CLARIFICATIONS</b>${t.addenda.map(a=>`<span>${esc(a)}</span>`).join('')}</div>`:'';
return`<article class="tender-card ${urgent?'urgent':''}" data-id="${esc(t.id)}" data-type="${esc([t.type,...(t.categories||[])].join(' '))}" data-search="${esc([t.title,t.issuer,t.ref,t.summary,...(t.categories||[])].join(' ').toLowerCase())}"><div class="card-top"><span class="status ${urgent?'urgent-status':'open'}">${typeLabel(t.type)}</span><span class="days-counter">${esc(daysLabel(t))}</span></div><div class="verification-row"><b>${esc(verify(t))}</b> · checked ${esc(t.verifiedAt||'10 September 2026')}</div><p class="issuer"><a href="issuer.html?issuer=${encodeURIComponent(t.issuerKey)}">${esc(t.issuer)}</a></p><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p><div class="meta">${t.ref?`<span>Ref: ${esc(t.ref)}</span>`:''}${cats}</div><div class="snapshot-mini"><div><small>Closing</small><b>${esc(t.deadlineLabel||'Confirm with issuer')}</b></div><div><small>Document fee</small><b>${esc(t.documentFee?.label||'Check notice')}</b></div><div><small>Bid security</small><b>${esc(t.bidSecurity?.label||'Check document')}</b></div><div><small>Site visit</small><b>${esc(t.siteVisit?.label||'Check document')}</b></div><div><small>Pre-bid</small><b>${esc(t.preBid?.label||'Check document')}</b></div></div>${addenda}${possible?`<div class="site-visit-offer"><span>MMGC SITE-VISIT SUPPORT</span><p>MMGC can assist with attendance where the issuing authority permits an authorised representative. If a compulsory visit has already passed, confirm eligibility before spending money on bid preparation.</p><a target="_blank" rel="noopener" href="${visitUrl(t)}">Ask MMGC about site visit →</a></div>`:''}<div class="card-actions primary-actions"><a class="summary-link" href="${detail}">Open Tender Snapshot</a><a class="cost-link" href="tender-calculator.html?tender=${encodeURIComponent(t.id)}">MMGC Can Cost This Tender</a></div><div class="utility-actions"><a target="_blank" rel="noopener" href="https://wa.me/?text=${share}">WhatsApp Share</a>${t.deadline?`<button type="button" data-action="calendar" data-id="${esc(t.id)}">Add to Calendar</button>`:''}<a href="checklists.html?type=${encodeURIComponent(t.type)}">Checklist</a>${possible?`<a target="_blank" rel="noopener" href="${visitUrl(t)}">Site Visit Help</a>`:''}<a target="_blank" rel="noopener" href="${esc(t.official)}">Official Source</a></div></article>`};
const open=tenders.filter(t=>!expired(t)).sort((a,b)=>{if(!a.deadline)return 1;if(!b.deadline)return-1;return new Date(a.deadline)-new Date(b.deadline)});if(container)container.innerHTML=open.map(card).join('');
const activeAlerts=[];open.forEach(t=>{const ms=remaining(t);if(ms!==null&&ms>=0&&ms<=twoDaysMs)activeAlerts.push({kind:'SUBMISSION DUE SOON',title:t.title,detail:daysLabel(t),href:`tender-details.html?id=${encodeURIComponent(t.id)}`});if(t.siteVisit?.date){const sv=new Date(t.siteVisit.date)-now;if(sv>=0&&sv<=twoDaysMs)activeAlerts.push({kind:'COMPULSORY SITE VISIT',title:t.title,detail:'Site visit is within 2 days.',href:visitUrl(t)})}});if(alerts&&activeAlerts.length)alerts.innerHTML=`<div class="wrap alerts-wrap">${activeAlerts.map(a=>`<a class="deadline-alert" href="${a.href}" ${a.href.startsWith('http')?'target="_blank" rel="noopener"':''}><span class="alert-badge">${a.kind}</span><strong>${esc(a.title)}</strong><span>${esc(a.detail)}</span><b>View →</b></a>`).join('')}</div>`;
const cards=()=>[...document.querySelectorAll('.tender-card')],apply=()=>{const q=(search?.value||'').trim().toLowerCase();let visible=0;cards().forEach(c=>{const show=(activeFilter==='all'||(c.dataset.type||'').toLowerCase().includes(activeFilter))&&(!q||(c.dataset.search||'').includes(q));c.classList.toggle('filtered-out',!show);if(show)visible++});if(countEl)countEl.textContent=visible;if(empty)empty.hidden=visible!==0};search?.addEventListener('input',apply);filterButtons.forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter||'all';filterButtons.forEach(x=>x.classList.toggle('active',x===b));apply()}));
const ics=t=>{const s=new Date(t.deadline),e=new Date(s.getTime()+1800000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//MMGC General Trading//Tender Desk//EN','BEGIN:VEVENT',`UID:${t.id}-${Date.now()}@mmgcgeneraltrading`,`DTSTAMP:${fmt(new Date())}`,`DTSTART:${fmt(s)}`,`DTEND:${fmt(e)}`,`SUMMARY:Tender Deadline - ${t.title}`,`DESCRIPTION:${t.issuer} | Reconfirm deadline and submission instructions with issuer.`,`URL:${t.official}`,'END:VEVENT','END:VCALENDAR'].join('\r\n')};document.addEventListener('click',e=>{const b=e.target.closest('[data-action="calendar"]');if(!b)return;const t=tenders.find(x=>x.id===b.dataset.id);if(!t?.deadline)return;const blob=new Blob([ics(t)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${t.id}-deadline.ics`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)});document.querySelectorAll('.main-nav a').forEach(l=>l.addEventListener('click',()=>{if(navToggle)navToggle.checked=false}));apply();
});